spring.datasource.url=jdbc:postgresql://db:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.open-in-view=false
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
file.upload-dir=${FILE_UPLOAD_DIR:/data/uploads/}
spring.rabbitmq.port=5672
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.username=demod
spring.rabbitmq.password=demo
spring.security.strategy=MODE_INHERITABLETHREADLOCAL
rabbitmq.queue.name=AY2526
rabbitmq.exchange.name=AY2526_exchange
rabbitmq.routing.key=AY2526_routing_key

# app.jwt.secret=${JWT_SECRET:dummy-jwt-secret-for-dev}
app.jwt.secret=${JWT_SECRET:lamwaihinisagoodguyhealwaysgotoschoolbybusandhewouldliketopreparedinnerforhisfamilyeveryday}

#Email service
spring.mail.host=mail14.serv00.com
spring.mail.port=587
spring.mail.username=kandajunko@kandajunko.serv00.net
spring.mail.password=P@ssw0rd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.smtp.connectiontimeout=5000
# spring.mail.properties.mail.smtp.timeout=5000
# spring.mail.properties.mail.smtp.writetimeout=5000