spring.datasource.url=jdbc:postgresql://db:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.open-in-view=false
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
file.upload-dir=${FILE_UPLOAD_DIR:/data/uploads/}
spring.rabbitmq.port=5672
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.username=demod
spring.rabbitmq.password=demo
# app.jwt.secret=${JWT_SECRET:dummy-jwt-secret-for-dev}
app.jwt.secret=${JWT_SECRET:lamwaihinisagoodguyhealwaysgotoschoolbybusandhewouldliketopreparedinnerforhisfamilyeveryday}

#Email service
spring.mail.host=smtp.example.com
spring.mail.port=587
spring.mail.username=your-email@example.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true