server {
    listen 80;
    
    # You can leave this as localhost, or change it to your AWS domain name later
    server_name localhost; 

    location / {
        proxy_pass http://ui:5173; # 'backend' must match your docker-compose service name
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    

    # 1. API Routing: Forward all /api/ requests to the Spring Boot container
    location /api/ {
        proxy_pass http://app:8080/swagger-ui/index.html; # 'backend' must match your docker-compose service name
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 2. Frontend Routing: Serve the compiled React static files
}